[package]
name = "doorbell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.70"
chrono = "0.4.24"
cidr = "0.2.1"
clap = { version = "4.2.4", features = ["derive"] }
config = "0.13.3"
http = "0.2.9"
log = "0.4.17"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
regex = "1.8.1"
serde = "1.0.160"
serde_derive = "1.0.160"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
