{
 "title": "Doorbell Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(doorbell_requests_total[1m])) * 60",
     "legendFormat": "requests/min"
    }
   ]
  },
  {
   "title": "request actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "floor(rate(doorbell_rule_actions[1m])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "4xx requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(doorbell_requests_total{status=~\"4..\"}[$__range]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Non-US Requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(doorbell_request_by_country{country!=\"US\"}[$__range]) > 0)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "requests per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(doorbell_requests_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# rules",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(doorbell_rules_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "/metrics errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "doorbell_metric_errors_total" }
   ]
  },
  {
   "title": "notifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(doorbell_notifications_total[$__range])) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "cache lookups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (name) (rate(doorbell_cache_lookups{status=\"hit\"}[$__rate_interval]))",
     "legendFormat": "{{name}} (hit)"
    },
    {
     "expr": "0 - (sum by (name) (rate(doorbell_cache_lookups{status!=\"hit\"}[$__rate_interval])))",
     "legendFormat": "{{name}} (miss)"
    }
   ]
  },
  {
   "title": "rules by source",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(source) (doorbell_rules_total)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Cache Entries",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "doorbell_cache_entries", "legendFormat": "{{name}}" }
   ]
  }
 ]
}