name: GeoIP Download

description: Downloads GeoIP City & Country Databases for Integration Tests

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: restore cache
      uses: actions/cache@v3
      id: geoip-cache
      with:
        path: geoip/download
        key: v1::geoip

    - name: Download Databases
      if: ${{ steps.geoip-cache.cache-hit != 'true' }}
      shell: bash
      run: ./scripts/download-geoip-databases.sh
      env:
        MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        DOWNLOAD_ONLY: "1"

    - name: Unpack Databases
      shell: bash
      run: ./scripts/download-geoip-databases.sh
      env:
        DOWNLOAD_ONLY: "0"

