name: GeoIP Download

description: Downloads GeoIP City & Country Databases for Integration Tests

inputs:
  maxmind_license_key:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: restore cache
      uses: actions/cache@v3
      id: geoip-cache
      with:
        path: geoip/download
        key: v1::geoip

    - name: Download Databases
      if: ${{ steps.geoip-cache.cache-hit != 'true' }}
      shell: bash
      run: |
        ./scripts/download-geoip-databases.sh
        find ./geoip -ls
      env:
        MAXMIND_LICENSE_KEY: ${{ inputs.maxmind_license_key }}
        NO_UNPACK: "1"

    - name: Unpack Databases
      shell: bash
      run: |
        ./scripts/download-geoip-databases.sh
        find ./geoip -ls
      env:
        NO_DOWNLOAD: "1"
