name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

  workflow_dispatch:
    inputs:
      openresty:
        description: 'OpenResty version (e.g. 1.21.4.1rc2)'
        required: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-openresty"

      - uses: leafo/gh-actions-luarocks@v4

      - run: luarocks lint doorbell-dev-1.rockspec
      - run: luarocks install luacheck
      - run: luacheck lib spec

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        openresty:
          - 1.21.4.1
    steps:
      - run: echo "OPENRESTY_VERSION=${{ matrix.openresty }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Setup OpenResty
        uses: thibaultcha/setup-openresty@main
        with:
          version: ${{ env.OPENRESTY_VERSION }}
