name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

  workflow_dispatch:
    inputs:
      openresty:
        description: 'OpenResty version (e.g. 1.21.4.1rc2)'
        required: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-openresty"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Lint rockspec file
        run: luarocks lint doorbell-dev-1.rockspec

      - name: Lint Lua files
        run: luacheck lib spec

  tests:
    name: Busted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        openresty:
          - 1.21.4.1
    steps:
      - run: echo "OPENRESTY_VERSION=${{ matrix.openresty }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Setup OpenResty
        uses: thibaultcha/setup-openresty@main
        with:
          version: ${{ env.OPENRESTY_VERSION }}
          test-nginx: false

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          withLuaPath: ${{ env.OPENRESTY_PREFIX }}/luajit

      - name: Install Main Luarocks Dependencies
        run: luarocks install --deps-only doorbell-dev-1.rockspec

      - name: Install Test Luarocks Dependencies
        run: luarocks test --prepare doorbell-dev-1.rockspec

      - name: Unit Tests
        run: busted run --unit

      - name: Integration Tests
        run: busted run --unit
